import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import '../css/normalize.css';
import '../css/webflow.css';
import '../css/sule-demo.webflow.css';
import './globals.css';
import ScrollToTop from "@/components/ScrollToTop";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body>
        <ScrollToTop />
        {children}
      </body>
    </html>
  );
}
